config/routes.rb
Stakeout::Application.routes.draw do

	resources :dashboards do
		resources :services
	end

	post 'dashboards/active',	as: 'active'
	
	# get "welcome/index",	as: 'home'
	get 'legal' => 'welcome#legal',	as: 'legal'
	get 'about' => 'welcome#about',	as: 'about'

	root to: 'dashboards#index'

end

app/models/service.rb
require 'capybara'
require 'capybara/poltergeist'
require 'thread'

class Service < ActiveRecord::Base

	belongs_to :dashboard

	validates_presence_of :name
	validates_presence_of :host

	# REFACTOR Nasty that this is a singleton, but it leaks a phantomjs process on #visit :(
	# https://github.com/jonleighton/poltergeist/issues/348
	BROWSER = Capybara::Session.new(:poltergeist)
	BROWSER_LOCK = Mutex.new

	PHOTO_OPTS  = {
	  :x => 0,          # top left position
	  :y => 0,
	  :w => 1280,       # bottom right position
	  :h => 1024,
	
	  :wait => 0.5,     # if selector is nil, wait 1 seconds before taking the screenshot
	  :selector => nil  # wait until the selector matches to take the screenshot
	}

	def expire_check
		self.checked_at = nil
		self.http_screenshot = nil
		self.save
	end

	def check_if_older_than(date)
		last = self.checked_at
		if last.nil? || last < date
			puts "Checking service #{self.name}."
			check
		else
			puts "Skipping service check for #{self.name}."
		end
	end

	def check
		self.http_screenshot = nil # Clear the old screenshots, regardless.

		if ping
			p = Net::Ping::External.new(self.host)
			if p.ping
				self.ping_last = (p.duration * 1000).to_i
			else
				self.ping_last = -1
			end
		end
		host = self.host
		path = self.http_path
		path = '/index.html' if(path.nil? || path == '')
		if self.http			
			uri = URI("http://#{self.host}#{self.http_path}")
			good = false
			begin
				Net::HTTP.start(uri.host, uri.port) do |http|
					request = Net::HTTP::Get.new uri
					response = http.request request # Net::HTTPResponse object
					code = response.code.to_i
					# puts "CODE: #{code}"
					self.http_path_last = (code >= 200 && code < 400)
				end
			rescue
				# Possibly a DNS failure or something.
				self.http_path_last = false
			end

			if http_xquery
				# TODO
			end
		end

		if self.https
			uri = URI("http://#{self.host}#{self.http_path}")
			good = false
			begin
				Net::HTTP.start(uri.host, uri.port) do |https|
					request = Net::HTTP::Get.new uri
					response = https.request request # Net::HTTPResponse object
					code = response.code.to_i
					# puts "CODE S: #{code}"
					self.https_path_last = (code >= 200 && code < 400)
				end
			rescue
				# Possibly a DNS failure or something.
				self.https_path_last = false
			end
		end

		if http_preview && (http || https)
			uri = URI("http://#{self.host}#{self.http_path}")
			if https
				uri = URI("https://#{self.host}#{self.http_path}")
			end
			begin
				BROWSER_LOCK.synchronize do
					puts "Visiting #{uri}"
					BROWSER.reset!
					BROWSER.visit uri.to_s
					sleep 0.100 # Brief artificial delay for rendering. :(
		
					tmp = Tempfile.new(['screenshot', '.png'])
					# puts tmp.path
					begin
						BROWSER.driver.render tmp.path,
						  :width  => PHOTO_OPTS[:w] + PHOTO_OPTS[:x],
						  :height => PHOTO_OPTS[:h] + PHOTO_OPTS[:y]
						self.http_screenshot = IO.read tmp.path
					ensure
						tmp.close # Close and delete the temporary file.
						tmp.unlink
					end
				end
			rescue
				# The visit will throw an exception if it times out.
			end
			
		end

		self.checked_at = Time.now
		self.save!
	end
	
	def known_good(since)
		known = false
		if !self.checked_at.nil? && (since.nil? || self.checked_at >= since)
			ping_good = (!self.ping || (!self.ping_last.nil? && self.ping_last >= 0 && self.ping_last <= self.ping_threshold))
			http_good = (!self.http || self.http_path_last)
			https_good = (!self.https || self.https_path_last)
			# TODO xquery_good = (self.http_xquery.nil? || self.http_xquery == '' || (self.http_xquery && TODO))
			if ping_good && http_good && https_good
				known = true
			end
		end
		known
	end
	
	def known_bad(since)
		known = false
		if (self.checked_at && since.nil?) || (!since.nil? && self.checked_at >= since)
			ping_bad = self.ping && !self.ping_last.nil? && (self.ping_last > self.ping_threshold || self.ping_last < 0)
			http_bad = self.http && !self.http_path_last
			https_bad = self.https && !self.https_path_last
			# xquery_bad = self.http_xquery && TODO
			if ping_bad || http_bad || https_bad
				known = true
			end
		end
		known
	end
	
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :set_service, only: [:show, :edit, :update, :destroy]


  # GET /services
  # GET /services.json
  def index
    period = 0
    if !params[:period].nil?
      period = params[:period].to_i
    end
    @dashboard = Dashboard.find(params[:dashboard_id])
    @services = @dashboard.services
    since = Time.now - period
    @services.each do |s|
      s.check_if_older_than(since)
    end
    render layout: false
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @dashboard = Dashboard.find(params[:dashboard_id])
    @service = Service.new
    @service.dashboard = @dashboard
    render partial: 'services/new'
  end

  # GET /services/1/edit
  def edit
    render partial: 'services/edit'
  end

  # POST
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        # format.html { redirect_to dashboards_path, notice: 'Service was successfully created.' }
				format.html { render partial: 'services/service', layout: false, locals: {service: @service} }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render partial: "services/new", layout: false, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT
  def update
    respond_to do |format|
      if @service.update(service_params)
        @service.expire_check
        format.html { render partial: 'services/service', layout: false, locals: {service: @service} }
        format.json { head :no_content }
      else
        format.html { render partial: "services/edit", layout: false, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE
  def destroy
    @service.destroy
    respond_to do |format|
      # format.html { redirect_to dashboards_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :dashboard_id, :host, :ping, :ping_threshold, :http, :https, :http_preview, :http_path, :http_xquery)

    end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_all.html.slim
= render :partial => 'services/service', :collection => dashboard.services.sort{|a,b| a.name <=> b.name}

app/views/services/_edit.html.slim
= render 'form'

app/views/services/_form.html.slim
= form_for [@service.dashboard, @service], :html => {class: 'form-horizontal', 'data-id' => @service.id} do |f|
	- if @service.errors.any?
		#error_explanation
			h2
				= pluralize(@service.errors.count, "error")
				|  prohibited this service from being saved:
			ul
				- @service.errors.full_messages.each do |msg|
					li = msg


	.control-group
		= f.hidden_field :dashboard_id, :value => params[:dashboard_id]
	
	.control-group
		= f.label :name, class: 'control-label'
		.controls
			= f.text_field :name, :required => true, :placeholder => 'Google', :required => true
	
	.control-group
		= f.label :host, class: 'control-label'
		.controls
			= f.text_field :host, :required => true, :placeholder => 'www.google.com', :required => true
			p.help-block Do not include protocol prefixes such as "http://".
	
	.control-group
		= f.label :ping, "Ping (ICMP)?", class: 'control-label'
		.controls
			= f.check_box :ping
	
	.control-group
		= f.label :ping_threshold, class: 'control-label'
		.controls
			= f.number_field :ping_threshold
			p.help-block The maximum number of milliseconds acceptable. Note that Stakeout will take a much longer time to ping the host that it would at the command line, so set this pretty high.
	
	.control-group
		= f.label :http, "HTTP GET?", class: 'control-label'
		.controls
			= f.check_box :http
			p.help-block All 2xx and 3xx-level response codes will be accepted. Redirects will not be followed!
	
	.control-group
		= f.label :https, "HTTPS GET?", class: 'control-label'
		.controls
			= f.check_box :https
			p.help-block All 2xx and 3xx-level response codes will be accepted. Redirects will not be followed. Important: SSL or JavaScript-related warning will result in a failure state! So if you're running self-signed certificates, you'll probably want to disable this.
	
	.control-group
		= f.label :http_preview, "Take screenshot?", class: 'control-label'
		.controls
			= f.check_box :http_preview
			p.help-block Grab a sweet screenshot when checking the status. HTTPS will be used instead, if enabled. Redirects will not be followed, and SSL and JavaScript-related warning or errors will prevent the screenshot from being taken.
	
	.control-group
		= f.label :http_path, "HTTP path", class: 'control-label'
		.controls
			= f.text_field :http_path, :placeholder => '/index.html'
			p.help-block If unsure, leave blank or try '/index.html'. When specifying a custom path, be sure to include the leading forward slash. 
	
	/ .control-group
		= f.label :http_xquery, 'XQuery Validation', class: 'control-label'
		.controls
			= f.text_field :http_xquery
			p.help-block If provided, the response must match this XQuery pattern.

app/views/services/_new.html.slim
= render 'form'

app/views/services/_service.html.slim
div id="service_#{service.id}" class="service #{service.http_screenshot.nil? ? :single : :double}"
	.status
		- if service.known_good(@since)
			= image_tag('green_large.png')
		- elsif service.known_bad(@since)
			= image_tag('red_large.png')
		- else
			= image_tag('grey_large.png')

	- if !service.http_screenshot.nil?
		img.img-polaroid.screenshot alt="Screenshot" src="data:image/png;base64,#{Base64.encode64(service.http_screenshot)}"

	h1 = service.name
	p.host
		- if service.https
			a href="https://#{service.host}#{service.http_path}" = "https://#{service.host}#{service.http_path}"
		- elsif service.http
			a href="http://#{service.host}#{service.http_path}" = "http://#{service.host}#{service.http_path}"
		- else
			= service.host



	- if service.checked_at
		p
			| As of  
			= distance_of_time_in_words_to_now service.checked_at
			|  ago: 
			- if service.http
				span.result class="#{service.http_path_last ? 'text-success' : 'text-error'}"
					| HTTP
			- if service.https
				span.result class="#{service.https_path_last ? 'text-success' : 'text-error'}"
					| HTTPS
			- if service.ping
				span.result class="#{(!service.ping_last.nil? && service.ping_last >= 0 && service.ping_last < service.ping_threshold) ? 'text-success' : 'text-error'}"
					| Ping
					-if !service.ping_last.nil?
						= service.ping_last < 0 ? ' (Failed)' : " (#{service.ping_last}ms)"


	- else
		p.muted Not checked.

	/ p
		| Added 
		= distance_of_time_in_words_to_now service.created_at
		|  ago.
	/ p
		| Modified 
		= distance_of_time_in_words_to_now service.updated_at
		|  ago.
	.btn-group.pull-right
		button.service_edit.btn data-id="#{service.id}" = text_with_icon('Edit', 'edit')
		button.service_remove.btn.btn data-id="#{service.id}" = text_with_icon('Remove', 'trash')

app/views/services/index.html.slim
= render partial: 'services/all', locals: {dashboard: @dashboard}

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dashboard:</b>
  <%= @service.dashboard_id %>
</p>

<p>
  <b>Name:</b>
  <%= @service.name %>
</p>

<p>
  <b>Host:</b>
  <%= @service.host %>
</p>

<p>
  <b>Ping:</b>
  <%= @service.ping %>
</p>

<p>
  <b>Http:</b>
  <%= @service.http %>
</p>

<p>
  <b>Http path:</b>
  <%= @service.http_path %>
</p>

<p>
  <b>Http xquery:</b>
  <%= @service.http_xquery %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>