config/routes.rb
Stakeout::Application.routes.draw do

	resources :dashboards do
		resources :services
	end

	post 'dashboards/active',	as: 'active'
	
	# get "welcome/index",	as: 'home'
	get 'legal' => 'welcome#legal',	as: 'legal'
	get 'about' => 'welcome#about',	as: 'about'

	root to: 'dashboards#index'

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base

	has_many :services,	:dependent => :destroy

	validates_presence_of :name
	validates_uniqueness_of :name

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :set_dashboard, only: [:show, :edit, :update, :destroy]

  before_action :ensure_active_dashboard_is_set, only: [:index]

  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dashboards }
    end
  end

	def check
		period = params[:client_period].to_i
		@since = period.minutes.ago
		d = Dashboard.find(session[:active_dashboard_id])
		d.services.each do |s|
			s.check
		end
		respond_to do |format|
      format.html { render 'services/index', layout: false }
    end
	end
	
	def active
		d = Dashboard.find(params[:id])
		set_as_active_dashboard d
	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: d }
	    end
	end


  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
    render partial: 'dashboards/edit'
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
				set_as_active_dashboard(@dashboard)
        format.html { redirect_to dashboards_path, notice: 'Dashboard was successfully created.' }
        format.json { render json: @dashboard, status: :created, location: @dashboard }
      else
        format.html { render partial: "dashboards/new", layout: false, status: :unprocessable_entity }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to dashboards_path, notice: 'Dashboard was successfully updated.' }
        format.json { render json: @dashboard }
      else
        format.html { render partial: "dashboards/edit", layout: false, status: :unprocessable_entity }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
		set_an_active_dashboard
    respond_to do |format|
      format.html { redirect_to dashboards_path }
      format.json { render	json: @active_dashboard }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.require(:dashboard).permit(:name)
    end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_edit.html.slim
= render 'form'

app/views/dashboards/_form.html.slim
= form_for(@dashboard, html: {'data-id' => @dashboard.id}) do |f|
	- if @dashboard.errors.any?
		#error_explanation
			h2
				= pluralize(@dashboard.errors.count, "error")
				|  prohibited this dashboard from being saved:
			ul
				- @dashboard.errors.full_messages.each do |msg|
					li = msg

	.field
		= f.label :name
		= f.text_field :name, :required => true, :placeholder => "My Dashboard"

app/views/dashboards/_new.html.slim
= render 'form'

app/views/dashboards/index.html.slim
- content_for :body_class do 'dashboard index' end

#dashboard

	#control_panel
		#bottom_group.btn-group
			= link_to 'Hide', '#', id: 'control_panel_visibility_button', class: 'btn'
			= link_to text_with_icon('Freshen', 'refresh'), '#', id: 'control_panel_refresh_button', class: 'btn'

		.widget
			h1 Dashboard

			form#dashboard_selection_form
				= select :active_dashboard, :id, @dashboards.collect {|n| [ n.name, n.id ] }.sort
			.btn-group
				= link_to text_with_icon('', 'plus'), new_dashboard_path, :id => 'new_dashboard_button', :class => 'btn btn-small'
				= link_to text_with_icon('', 'edit'), dashboard_path(@active_dashboard), id: :edit_dashboard_button, class: "btn btn-small"
				= link_to text_with_icon('', 'trash'), dashboard_path(@active_dashboard), id: :delete_dashboard_button, class: "btn btn-small"
				= link_to text_with_icon("Add Service", 'plus'), new_dashboard_path, :id => 'new_service_button', :class => 'btn btn-small btn-success'


		.widget
			h1
				| Refresh (
				span#currentValue 0
				| m)
			input#refresh_period type="range" min="1" max="60"
			#refresh_period_knob

		.clearfix


	#refresh_in_progress_dialog.modal.hide.fade
		.modal-header
			/ button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times;
			h3 Be cool, honey bunny!
		.modal-body
			p Services are being rechecked from the server. Hold, please!
			div.progress.progress-striped.active
				div.bar style="width: 100%;"
			p.muted If you really hate seeing this dialog all the time, dial down your refresh interval. We only update statuses and screenshots upon your request, and never more frequently than in 1-minute intervals to respect service providers.
			p.muted The slowest things to capture, by far, are screenshots. So if you want super-fast updates every minute for a lot of services, you'll want to disable the screenshot feature. On the plus side, though, screenshots are cached until the next status check, so if you're running a popular dashboard with a lot of people watching it, you'll have to wait less since someone else probably ran the screenshots for you.
		.modal-footer

	
	#new_dashboard_dialog.modal.hide.fade
		.modal-header
			button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times;
			h3 Create a new dashboard!
		.modal-body
			- @dashboard = Dashboard.new
			= render partial: 'dashboards/form'
		.modal-footer
			button class="submit btn btn-primary" Save

	#edit_dashboard_dialog.modal.hide.fade
		.modal-header
			button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times;
			h3 Edit dashboard.
		.modal-body
			/ Form loaded dynamically.
		.modal-footer
			button class="submit btn btn-primary" Save

	#new_service_dialog.modal.hide.fade
		.modal-header
			button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times;
			h3 Monitor a new service.
		.modal-body
			/ Form loaded dynamically.
		.modal-footer
			button class="submit btn btn-primary" Save

	#edit_service_dialog.modal.hide.fade
		.modal-header
			button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times;
			h3 Edit service monitoring.
		.modal-body
			/ Form loaded dynamically.
		.modal-footer
			button class="submit btn btn-primary" Save
	

	#services.row-fluid
		/ Only loaded via ajax!
		/ - if @active_dashboard
		/ 	= render partial: 'services/all', :locals => {:dashboard => @active_dashboard}
		/ - else
		/ 	p Whoa whoa whoa... you don't have any dashboards set up!
		.clearfix
	javascript:
		$(function() {
			$('#refresh_in_progress_dialog').modal('show');
		});

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dashboard.name %>
</p>


<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>